// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmUEAR1SB7bf29XoGNpOExo_GWoNl68J8',
    appId: '1:903921644523:android:8b1be795cfa3b71a079fae',
    messagingSenderId: '903921644523',
    projectId: 'leg-barkr',
    storageBucket: 'leg-barkr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6haaqDGLGt5gYLc_z1r0P-jWl0bF3Xlc',
    appId: '1:903921644523:ios:9294b2d611ff71fc079fae',
    messagingSenderId: '903921644523',
    projectId: 'leg-barkr',
    storageBucket: 'leg-barkr.appspot.com',
    iosClientId: '903921644523-cq15mvp7kj64spro7ugkh781kvp4bm42.apps.googleusercontent.com',
    iosBundleId: 'com.legbarkr.app',
  );
}
